default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  port: 5432

development:
  <<: *default
  database: qcx_test_development

test:
  <<: *default
  database: qcx_test_test

production:
  <<: *default
  database: qcx_test_production
